name: Resuable Workflow 1 (Print message)

on:
  
  workflow_dispatch:
    inputs:
      phrase:
        description: "String to use in printed message"
        required: false
        type: string
        default: "...but you didn't specify a value"
  
  # Must have workflow_call in order for workflow to be reusable
  workflow_call:
    inputs:
      phrase:
        type: string
        default: "...nothing (you didn't specify a value)"

env:
  YELLOW: "\033[0;33m"
  DONE: "\033[0m"
        
jobs:
  print-message:
    name: Print message
    runs-on: ubuntu-latest
    
    steps:
      - name: Print the message
        run: | 
          echo "Printing a message with your 'phrase' input, which you defined as '${{ inputs.phrase }}'."
          echo "You called this workflow via the '${{ github.event_name }}' event."
          echo -e "${YELLOW} This text will be yellow. ${DONE}"