# Scenario:
# A large organization "org-mushroom-kingdom" owns an app called "Toad Town News" 
# The frontend and backend are in their own repositories. Future repositiories are an inevitability.
# There is also a separate repository solely for resuable workflows used for the development of Toad Town News   
# In this organization, it is a standard across repositories to include a specific changelog file in their release branch  
# This file should begin with CHANGELOG, followed by a dash (-), followed by the piece of the project they're working on
# Repositories and release branches are named in a standardized way. The changelog file name should be formed from a combination of these.
# ex. The frontend repo is named org-mk/ttn-frontend. 
#     A release branch in it is named release/v1.0. 
#     The changelog file should be named CHANGELOG-frontend-v1.0.txt

# This all means I have to move this crap over to a different repo. Womp womp

name: Resuable Workflow 3 (Call on script in reusable workflow repo)

on:
  
  workflow_dispatch:

  workflow_call:

jobs:
  something:
    name: "Something"
    runs-on: ubuntu-latest
    env:
        REPO: ${{ github.repository }}
    steps:
      
      # This will checkout the caller repo if event is workflow_call?
        - name: Checkout repo
          uses: actions/checkout@v4
        
        - name: Echo relevant vars
          run: echo "TBD" 

        - name: repo sanity check
          run: echo "TBD"


